# Generated by Django 3.2.20 on 2023-07-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fourth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.CharField(choices=[('Indoors', 'Indoors'), ('Outdoors', 'Outdoors')], default='Indoors', max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='RestaurantTable',
        ),
    ]
